### ISSUE TITLE
Dependancy is getting installed as a devDependancy?

### ISSUE THREAD

**Issue by rforster-dev** [browserstack/browserstack-cypress-cli#584]
When using browserstack and cypress, in our package we have `dependancies`, to which if we specify them as:

```
  "npm_dependencies": {
      "my-dependancy": "^x.x.x",
```

I can see in the package.json that gets uploaded it actually changes it to a `devDependancy` which is incorrect.

How do we ensure that dependancies we are specifying are installed correctly?

**Comment by ELflamer** [comment]
Hey there,

Please install the packages and configure the dependencies and dev dependencies separately. 

` "dependencies": {
    "chai": "^4.5.8",
  },
  "devDependencies": {
    "@wdio/mocha-framework": "^7.5.0"
  }`
  
  This should resolve the issue.

**Comment by rforster-dev** [comment]
Thanks for the quick response.

In the package.json, we are specifying it like that. So it looks like (example):

```
dependancies: {
"node-fetch": "^x.x.xx",
...
}

and in my browserstack.json it has:

```
  "npm_dependencies": {
      "node-fetch": "^x.x.x",
}
```

But it still gets uploaded to browserstack through the cli as a devDependancy? As the test in the Browserstack says it cant find the module.

**Comment by rforster-dev** [comment]
https://github.com/browserstack/browserstack-cypress-cli/blob/425f260bc3b27555d44f9c3c82cf7c476b8123c1/bin/helpers/packageInstaller.js#LL33C11-L33C11 on this line I can see that it simply assumes all dependancies specified in `npm_dependancies` should be devDependancies.

This is incorrect I would say, and should be up to the consumer to decide on if we require dependancies or devdevependancies?
